### ISSUE TITLE
dataset - team: UQ-GD

### ISSUE THREAD

**Issue by MegZee** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#11]
I cant seem to find the dataset for the challenge.

**Comment by AISG-Wesley** [comment]
Hi MegZee, due to the sensitive nature of the content, no datasets will be provided for model development. Participants are required to source for relevant datasets, devise data augmentation methods, or employ automated meme generation techniques to curate an appropriate dataset for model training and testing.
