### ISSUE TITLE
JK-Piece--Request to show the number of images processed before runtime limit exceeded error.

### ISSUE THREAD

**Issue by Jean-KOUAGOU** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#17]
Dear technical support,

My previous submissions exceeded the runtime limit, and therefore an error was raised. 
I can only see ``Time Limit Exceeded``.
Would it be possible to show how many images are left before the time limit is exceeded? This would help design an optimal model in terms of runtime.

Instead of showing ``"Running"``, it would be helpful to have a progress bar like ``Processed 32/1700``

**Comment by AISG-Wesley** [comment]
We cannot tell any participant how many images they may have processed at any point of time because we only do the scoring at the end of the running of the Docker or when the Time Limit has exceeded.  Scoring is done on a all-or-nothing basis -- there is no partial credit.
 
You may choose to use logging to `stderr` to help you determine this, as well as the information from https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#max-docker-container-runtime .
 
Do note that if we determine that `stderr` contains *too much* information that can compromise the hidden data set, we will exercise our right to decline releasing the said logs.
