### ISSUE TITLE
Output format error UQ-GD team

### ISSUE THREAD

**Issue by PietroBernardelle** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#28]
Hi, our team is getting an output format error.

Could you please send over the logs and stdout and convey what exactly is the reason for an output error?
After building the docker locally on our machine everything works fine, that is why we are contacting you.
Our submission id is the following: a8fa6fb9-e3eb-42d3-980c-82d2d25e1e5c

Thanks

**Comment by AISG-Wesley** [comment]
No, we will not be releasing `stdout`. We may only release `stderr` logs as highlighted in https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#logging-output-stderr .  

The reason for the output error is because your submission did not fulfill the requirements stipulated in https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#solution-output-stdout .

While we may release the logs from `stderr`, in this instance we have decided not to because the content in `stderr `cannot be safely ascertained to not be revealing the dataset due to its extensive nature.

However, as a one-time effort to assist you, we will release the following summary as to what we see in `stderr`, making no guarantees that this is an actual cause.

There are several instances of `UNKNOWN:  JIT compilation failed. `error messages.

We will not release any more information about the logs from `stderr` for this submission.
