### ISSUE TITLE
Humans of DSCIG - bramyeon - Request for logs

### ISSUE THREAD

**Issue by bramyeon** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#81]
Requesting the log for submission ID `38d6d348-4c38-450e-9c4c-db53e2f33d88`. Thank you!

**Comment by AISG-Wesley** [comment]
Hi bramyeon, we are not able to release the logs for this submission due to information leakage of the dataset in the logging at a per-input level.

**Comment by bramyeon** [comment]
Thank you for the reply. Could you just briefly mention if, at the beginning of the inference, it says anything like "Model Loading Failed"? 

And just the relative frequency of our log writing "Text Recognition Failed" and "Classification Failed" in the stderr?

We really need this information for debugging, and actually, the log just prints out this and the inference time for each line. Thanks in advance!

**Comment by AISG-Wesley** [comment]
Hi bramyeon, we have noted that the submission was successfully completed with a score. Therefore, we consider it a successful submission, rather than one that requires debugging. While I understand you are seeking further assistance, particularly with the logs, our challenge protocol does not include debugging support. I appreciate your understanding,

**Comment by bramyeon** [comment]
Thank you.
